/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ni.com.userApi;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
//@EnableSwagger2
public class App {
  public static void main(String[] args) {
    SpringApplication.run(App.class, args);
  }

//  @Bean
//  public Docket usuarioApi() {
//    return new Docket(DocumentationType.SWAGGER_2)
//        .select()
//        .apis(RequestHandlerSelectors.basePackage("ni.com.userApi.controller.authentication"))
//        .build();
//  }
}
