jwt:
    secret: todoEsPosible
token:
    tiempo: 10
server:
    error:
        include-message: always
    servlet:
        context-path: '/auth/${VERSION:v1}'
spring:
    datasource:
        driverClassName: org.h2.Driver
        password: '${PASSWORD_DB:1234}'
        url: jdbc:h2:mem:testdb
        username: '${USER_DB:sa}'
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: false
                web-allow-others: false
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: create
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
        throw-exception-if-no-handler-found: true
